"""Contracts for replacing the deterministic planner/environment with real systems.

No provider SDK is imported here. External credentials and models are deliberately kept
out of the reproducible core.
"""
from __future__ import annotations
from typing import Protocol, Any
from .schemas import ActionProposal, AgentState

class ModelAdapter(Protocol):
    def propose(self, task: str, state: AgentState, observation: dict[str,Any]) -> ActionProposal: ...
    def diagnose(self, trajectory: list[dict], mismatch: dict) -> dict: ...
    def replan(self, task: str, state: AgentState) -> list[ActionProposal]: ...

class BrowserAdapter(Protocol):
    def screenshot(self) -> bytes: ...
    def accessibility_tree(self) -> dict: ...
    def execute(self, action) -> Any: ...
    def export_state(self) -> dict: ...
    def import_state(self, state: dict) -> None: ...
