from __future__ import annotations
from typing import Protocol
from ..schemas import Action, ActionResult

class Environment(Protocol):
    supports_rollback: bool
    def reset(self, task): ...
    def observe(self) -> dict: ...
    def execute(self, action: Action) -> ActionResult: ...
    def export_state(self) -> dict: ...
    def import_state(self, state: dict) -> None: ...
    def apply_perturbation(self, kind: str) -> None: ...
    def grade(self) -> bool: ...
